name: Maven Integration Tests

on: [push, pull_request]

jobs:
  maven-integration-tests:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install maven
      run: yum -y install maven
    - name: run integration-tests
      run: mvn -P\!cfg-module-dist -P\!cfg-module-rpm -P\!module-test clean integration-test
